version: '3'

services:
  mysqla:
    image: mysql:8.0      
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: currency
      MYSQL_USER: ankit
      MYSQL_PASSWORD: ankit123
    volumes:
      - mysql_data:/var/lib/mysql 
    ports:
      - "3306:3306"
    networks:
      - currency-network 
      
  identity:
    image: negiankit705/microservices-idenity:0.0.1-SECURITY
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - currency-network
    depends_on:
      - mysqla
    environment:
      #EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      EUREKA.CLIENT.FETCHREGISTRY: "true"
      #MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqla:3306/currency
      SPRING_DATASOURCE_USERNAME: ankit
      SPRING_DATASOURCE_PASSWORD: ankit123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      
networks:
  currency-network:

volumes:
  mysql_data: